steps:
  - name: ":ruby: Verify catalogues"
    key: verify-catalogues
    command:
      - bundle install
      - bundle exec rake verify
    agents:
      queue: "oss-deploy"
    plugins:
      - docker#v5.11.0:
          image: "ruby:3.4"

  - name: ":nodejs: Verify package"
    key: verify-package
    command: node .buildkite/verify-package.mjs
    agents:
      queue: "oss-deploy"
    plugins:
      - docker#v5.11.0:
          image: "node:22"

  - name: ":shipit: Release images and package"
    command: ".buildkite/release.sh"
    branches: "main"
    depends_on:
      - verify-catalogues
      - verify-package
    concurrency: 1
    concurrency_group: "buildkite-emojis/release"
    agents:
      queue: "oss-deploy"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::${ROLE_ACCOUNT_ID}:role/pipeline-buildkite-emojis
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
            - build_branch
      - aws-ssm#v1.0.0:
          parameters:
            NPM_TOKEN: /prod/buildkite-emojis/npm-token
